routes/web.php
<?php

use App\Http\Controllers\BooksController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\PublisherExportExcel;
use App\Http\Controllers\PublishersController;
use App\Http\Controllers\UserController;
use App\Models\Category;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

// Route::get('categories', [CategoriesController::class, 'index'])->name('categories.index');
// Route::get('categories/create', [CategoriesController::class, 'create'])->name('categories.create');
// Route::post('categories', [CategoriesController::class, 'store'])->name('categories.store');
// Route::get('categories/{id}', [CategoriesController::class, 'edit'])->name('categories.edit');
// Route::put('categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
// Route::delete('categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');

Route::resource('categories', CategoriesController::class)->middleware('auth');
Route::resource('publishers', PublishersController::class)->except('show')->middleware('auth');
Route::get('publishers/export-excel', PublisherExportExcel::class)->name('publishers.export-excel')->middleware('auth');
Route::resource('books', BooksController::class)->middleware('auth');

require __DIR__.'/auth.php';

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    public $dates = ['published_at'];

public function category()
{
    return $this->belongsTo(Category::class);
}

public function publisher()
{
    return $this->belongsTo(Publisher::class);
}
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Category;
use App\Models\Publisher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return datatables()
                ->eloquent(Book::query()->with('publisher', 'category'))
                ->editColumn('cover', function ($model) {
                    return '<img src="' . asset($model->cover) . '" />';
                })
                ->editColumn('published_at', function ($model) {
                    return $model->published_at->format('Y-m-d');
                })
                ->addColumn('action', 'books.action')
                ->rawColumns(['cover', 'action'])
                ->addIndexColumn()
                ->toJson();
        }

        return view('books.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create', [
            'categories' => Category::get(),
            'publishers' => Publisher::get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cover = null;

        if ($request->hasFile('cover')) {
            $cover = $request->file('cover')->store('cover');
        }

        Book::create([
            'category_id' => $request->category_id,
            'publisher_id' => $request->publisher_id,
            'title' => $request->title,
            'slug' => Str::slug($request->title),
            'cover' => $cover,
            'published_at' => $request->published_at,
        ]);

        session()->flash('success', 'Book added successfully.');

        return redirect()->route('books.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('books.edit', [
            'book' => Book::find($id),
            'categories' => Category::get(),
            'publishers' => Publisher::get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = Book::find($id);

        $cover = $book->cover;

        if ($request->hasFile('cover')) {
            if (Storage::exists($cover)) {
                Storage::delete($cover);
            }

            $cover = $request->file('cover')->store('cover');
        }

        $book->update([
            'category_id' => $request->category_id,
            'publisher_id' => $request->publisher_id,
            'title' => $request->title,
            'slug' => Str::slug($request->title),
            'cover' => $cover,
            'published_at' => $request->published_at,
        ]);

        session()->flash('success', 'Book updated.');

        return redirect()->route('books.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);

        if ($book->cover !== null) {
            Storage::delete($book->cover);
        }

        $book->delete();
    }
}

resources/views/books/action.blade.php
<a href="{{ route('books.edit', $model) }}" class="btn btn-info">Edit</a>
<button class="btn btn-danger" data-id="{{ $model->id }}" id="delete">Delete</button>

resources/views/books/create.blade.php
<x-templates.default>
    <x-slot:pretitle>Add Book</x-slot:pretitle>
    <x-slot:title>Books</x-slot:title>

    <div class="row row-cards">
        <div class="col-12">
            <form action="{{ route('books.store') }}" class="card" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card-header">Add Book</div>
                <div class="card-body">
                   <x-input-form name="title" placeholder="Book Title"/>
                   <div class="mb-3">
                    <label class="form-label">Cover</label>
                    <input type="file" name="cover" id="" class="form-control">
                   </div>
                   <x-input-form name="published_at" type="date" placeholder="Release date"/>
                   <div class="mb-3">
                        <label for="" class="form-label">Category</label>
                        <select name="category_id" id="" class="form-select">
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                   </div>
                   <div class="mb-3">
                        <label for="" class="form-label">Publisher</label>
                        <select name="publisher_id" id="" class="form-select">
                            @foreach ($publishers as $publisher)
                                <option value="{{ $publisher->id }}">{{ $publisher->name }}</option>
                            @endforeach
                        </select>
                   </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Save" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</x-templates.default>

resources/views/books/edit.blade.php
<x-templates.default>
    <x-slot:pretitle>Edit Book</x-slot:pretitle>
    <x-slot:title>Books</x-slot:title>

    <div class="row row-cards">
        <div class="col-12">
            <form action="{{ route('books.update', $book) }}" class="card" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-header">Edit Book</div>
                <div class="card-body">
                   <x-input-form name="title" :currentData="$book->title" placeholder="Book Title"/>
                   <div class="mb-3">
                    <label class="form-label">Cover</label>
                    <input type="file" name="cover" id="" class="form-control">
                   </div>
                   <x-input-form name="published_at" :currentData="$book->published_at->format('Y-m-d')" type="date" placeholder="Release date"/>
                   <div class="mb-3">
                        <label for="" class="form-label">Category</label>
                        <select name="category_id" id="" class="form-select">
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}" @if($category->id === $book->category_id) selected @endif>{{ $category->name }}</option>
                            @endforeach
                        </select>
                   </div>
                   <div class="mb-3">
                        <label for="" class="form-label">Publisher</label>
                        <select name="publisher_id" id="" class="form-select">
                            @foreach ($publishers as $publisher)
                                <option value="{{ $publisher->id }}" @if($publisher->id === $book->publisher_id) selected @endif>{{ $publisher->name }}</option>
                            @endforeach
                        </select>
                   </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Save" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</x-templates.default>

resources/views/books/index.blade.php
<x-templates.default>
    <x-slot:pretitle>Data Book</x-slot:pretitle>
    <x-slot:title>Books</x-slot:title>
    <x-slot:page_action>
        <a href="{{ route('books.create') }}" class="btn btn-primary">Add Book</a>
    </x-slot:page_action>
    <x-slot:extraStyles>
        <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.18/sweetalert2.min.css"
            integrity="sha512-CJ5goVzT/8VLx0FE2KJwDxA7C6gVMkIGKDx31a84D7P4V3lOVJlGUhC2mEqmMHOFotYv4O0nqAOD0sEzsaLMBg=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
    </x-slot:extraStyles>

    <div class="row row-cards">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-vcenter card-table" id="dataTable">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Cover</th>
                                    <th>Published</th>
                                    <th>Category</th>
                                    <th>Publisher</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <x-slot:extraScripts>
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

        <script>
            $(function() {
                $('#dataTable').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{!! route('books.index') !!}', // memanggil route yang menampilkan data json
                    columns: [{ // mengambil & menampilkan kolom sesuai tabel database
                        data: 'DT_RowIndex',
                        name: 'id'
                    }, {
                        data: 'title',
                        name: 'title'
                    }, {
                        data: 'cover',
                        name: 'cover'
                    }, {
                        data: 'published_at',
                        name: 'published_at'
                    }, {
                        data: 'category.name',
                        name: 'category_name'
                    }, {
                        data: 'publisher.name',
                        name: 'publisher_name'
                    }, {
                        data: 'action',
                        name: 'action'
                    }, ]
                });
            });
        </script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.18/sweetalert2.min.js"
            integrity="sha512-98hK38IvWQC069FFbq/la6NaBj4TGplZ118B+bFVOxsBQQL4EqKUWw9JkNh8Lem7FCGkLCxgr81q+/hRIemJCw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
            $('#dataTable').on('click', 'button#delete', function(e) {
                e.preventDefault();
                var id = $(this).data('id');

                Swal.fire({
                    title: 'Kamu yakin hapus data ini?',
                    text: "Data yang dihapus tidak bisa dikembalikan!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ok, Delete!',
                    cancelButtonText: 'Cancel',
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            type: 'DELETE',
                            url: '/books/' + id,
                            data: {
                                'id': id,
                                '_token': "{{ csrf_token() }}"
                            },
                            success: function(response) {
                                if (response.error) {
                                    Swal.fire(
                                        'Gagal menghapus data!', response.error, 'error'
                                    )
                                } else {
                                    Swal.fire(
                                        'Dihapus!', 'Data berhasil dihapus.', 'success'
                                    )

                                    location.reload(true);
                                }
                            },
                        });
                    }
                })
            })
        </script>

    </x-slot:extraScripts>
</x-templates.default>