routes/web.php
<?php

use App\Http\Controllers\BooksController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\PublisherExportExcel;
use App\Http\Controllers\PublishersController;
use App\Http\Controllers\UserController;
use App\Models\Category;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

// Route::get('categories', [CategoriesController::class, 'index'])->name('categories.index');
// Route::get('categories/create', [CategoriesController::class, 'create'])->name('categories.create');
// Route::post('categories', [CategoriesController::class, 'store'])->name('categories.store');
// Route::get('categories/{id}', [CategoriesController::class, 'edit'])->name('categories.edit');
// Route::put('categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
// Route::delete('categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');

Route::resource('categories', CategoriesController::class)->middleware('auth');
Route::resource('publishers', PublishersController::class)->except('show')->middleware('auth');
Route::get('publishers/export-excel', PublisherExportExcel::class)->name('publishers.export-excel')->middleware('auth');
Route::resource('books', BooksController::class)->middleware('auth');

require __DIR__.'/auth.php';

app/Models/Publisher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Publisher extends Model
{
    use HasFactory;

    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/PublishersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Publisher;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class PublishersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return datatables()
                ->eloquent(Publisher::query())
                ->addColumn('action', 'publishers.action')
                ->toJson();
        }

        return view('publishers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('publishers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => ['required'],
            'address' => ['required'],
            'phone' => ['required', 'numeric'],
        ]);

        Publisher::create([
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'address' => $request->address,
            'phone' => $request->phone,
        ]);

        session()->flash('success', 'Publisher added successfully.');

        return redirect()->route('publishers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('publishers.edit', [
            'publisher' => Publisher::find($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => ['required', Rule::unique('publishers', 'slug')->ignore($id)],
            'address' => ['required'],
            'phone' => ['required', 'numeric'],
        ]);

        $publisher = Publisher::find($id);

        $publisher->update([
            'name' => $request->name,
            'slug' => Str::slug($request->name),
            'address' => $request->address,
            'phone' => $request->phone,
        ]);

        session()->flash('success', 'Publisher updated successfully.');

        return redirect()->route('publishers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $publisher = Publisher::find($id);
        $publisher->delete();
    }
}

resources/views/publishers/action.blade.php
<a href="{{ route('publishers.edit', $model) }}" class="btn btn-info">Edit</a>
<button data-id="{{ $model->id }}" id="delete" class="btn btn-danger">Delete</button>

resources/views/publishers/create.blade.php
<x-templates.default>
    <x-slot:pretitle>Add Publisher</x-slot:pretitle>
    <x-slot:title>Publishers</x-slot:title>

    <div class="row row-cards">
        <div class="col-12">
            <form action="{{ route('publishers.store') }}" class="card" method="post">
                @csrf
                <div class="card-header">Add Publisher</div>
                <div class="card-body">
                   <x-input-form name="name" placeholder="Publisher Name"/>
                   <x-input-form name="address" placeholder="Publisher Address"/>
                   <x-input-form name="phone" placeholder="Publisher Phone"/>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Save" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</x-templates.default>

resources/views/publishers/edit.blade.php
<x-templates.default>
    <x-slot:pretitle>Edit Publisher</x-slot:pretitle>
    <x-slot:title>Publishers</x-slot:title>

    <div class="row row-cards">
        <div class="col-12">
            <form action="{{ route('publishers.update', $publisher) }}" class="card" method="post">
                @csrf
                @method('PUT')
                <div class="card-header">Edit Publisher</div>
                <div class="card-body">
                   <x-input-form name="name" :currentData="$publisher->name" placeholder="Publisher Name"/>
                   <x-input-form name="address" :currentData="$publisher->address" placeholder="Publisher Address"/>
                   <x-input-form name="phone" :currentData="$publisher->phone" placeholder="Publisher Phone"/>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Save" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</x-templates.default>

resources/views/publishers/index.blade.php
<x-templates.default>
    <x-slot:pretitle>Data Publisher</x-slot:pretitle>
    <x-slot:title>Publishers</x-slot:title>
    <x-slot:page_action>
        <a href="{{ route('publishers.create') }}" class="btn btn-primary">Add Publisher</a>
        <a href="{{ route('publishers.export-excel') }}" class="btn btn-success">Export Excel</a>
    </x-slot:page_action>
    <x-slot:extraStyles>
        <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.18/sweetalert2.min.css" integrity="sha512-CJ5goVzT/8VLx0FE2KJwDxA7C6gVMkIGKDx31a84D7P4V3lOVJlGUhC2mEqmMHOFotYv4O0nqAOD0sEzsaLMBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </x-slot:extraStyles>
    <div class="row row-cards">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-vcenter card-table" id="dataTable">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th>Address</th>
                                    <th>Phone</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-slot:extraScripts>
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

        <script>
            $(function() {
                $('#dataTable').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{!! route('publishers.index') !!}', // memanggil route yang menampilkan data json
                    columns: [{ // mengambil & menampilkan kolom sesuai tabel database
                            data: 'id',
                            name: 'id'
                        },
                        {
                            data: 'name',
                            name: 'name'
                        },
                        {
                            data: 'slug',
                            name: 'slug'
                        },
                        {
                            data: 'address',
                            name: 'address'
                        },
                        {
                            data: 'phone',
                            name: 'phone'
                        },
                        {
                            data: 'action',
                            name: 'action'
                        }
                    ]
                });
            });
        </script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.18/sweetalert2.min.js" integrity="sha512-98hK38IvWQC069FFbq/la6NaBj4TGplZ118B+bFVOxsBQQL4EqKUWw9JkNh8Lem7FCGkLCxgr81q+/hRIemJCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
            $('#dataTable').on('click', 'button#delete', function(e) {
                e.preventDefault();
                var id = $(this).data('id');

                Swal.fire({
                    title: 'Kamu yakin hapus data ini?',
                    text: "Data yang dihapus tidak bisa dikembalikan!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ok, Delete!',
                    cancelButtonText: 'Cancel',
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            type: 'DELETE',
                            url: '/publishers/' + id,
                            data: {
                                'id': id,
                                '_token': "{{ csrf_token() }}"
                            },
                           success: function(response) {
                                if (response.error) {
                                    Swal.fire(
                                        'Gagal menghapus data!',
                                        response.error,
                                        'error'
                                    )
                                } else {
                                    Swal.fire(
                                        'Dihapus!',
                                        'Data berhasil dihapus.',
                                        'success'
                                    )

                                    location.reload(true);
                                }
                            },
                        });
                    }
                })
            })
        </script>

    </x-slot:extraScripts>
</x-templates.default>